language: python 
python:
- 3.5
install:
- pip install six pyyaml requests markdown2 jinja2
script:
- python validate_entries.py
deploy:
  provider: script
  script: site_generator/travis_deploy
  on:
    repo: dotastro/hacks-collectoron:
    all_branches: true
env:
  global:
    secure: mKuUlffI5Pze+o8QwyGxePSFOQuHzHzLe4c/ImHMG6gCFZQxl6XPYLy0hzlSM5uKd7rDSoXI5njdh/a02D6NYBiUKSbMKK/G9taTfTlB05uO9jtzYQtQ9/embHJRPIpf55gNsvVRVQ7aNkzbsXA8m5m6JKeXztEwItIwsGdDbxRv7zdih97yqfAKGHwl/0SDg7vdIUQJZGSscUl1MhO2Gsi83JhzGpmP3vzz2suj9Uouh7V+X62h2MVrx/cr9FyxwydqXo3Oar1cL1knLZT2d4tj4fZLan0RKnkHHhM9euBSNbENl2V0vgKh82DHSvyzstjO3UwIw121NMMPr+5kIg8hZ0/HLRa/Nwd0oX6MiOrjmeEelCPz1YefzzPXYRk88eRFlSF6kaM49E8rIkmbT/XJrkiZQ4wUKuQ0S3aHV2asZPnelDO0Pqy6++YQ3MIm3yRs+xAGoLmED7CM5S7v99HQMkSJH1eM4AP08ElBAS0qI1MWXkN6R6yT9DD3uYhjk7eYJSiOoxYig6ZC6XlzE1FwaGwBIO2BkVS8BbOUUU0u0CSmdyW4B+6NTIWqCmyRWcl/RrT3CafL7FdrKutT0Jw4QTMZMjhkSYEukTfSlmq/ZsG26QyAE7T2NbOpwxd1KO+ipNbRm4wP/UUr6xqjHHM5KtdJJPbjNepPhOZblOk=
